# Generated by Django 4.2.7 on 2023-12-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username1", models.CharField(max_length=50)),
                ("username2", models.CharField(max_length=50)),
                ("phone1", models.IntegerField(unique=True)),
                ("phone2", models.IntegerField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("uid", models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
